server:
  port: 9999
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_cinemaManagement?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
  #graphql:
    #date:
      #format: yyyy-MM-dd HH:mm:ss
    #graphiql:
      #enabled: true
logging:
  level:
    org.springframework.web: DEBUG
    ma.gov.managementCinema: DEBUG
